### ISSUE TITLE
app crash when give root to mbtool

### ISSUE THREAD

**Issue by tone361** [chenxiaolong/DualBootPatcher#986]
Everytime I give root to mbtool app crash...my phone is energy phone colors based on mt6572..

**Comment by chenxiaolong** [comment]
Can you please make it crash again and attach `crash.log` in `/sdcard/MultiBoot`?

**Comment by klorinczi** [comment]
[crash_log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/1674290/crash_log.zip)
I also had crashes.
Not sure if the same case. 
Attaching crash.log

[crash_log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/1674287/crash_log.zip)

**Comment by benkhouya** [comment]
Same here "app crash" 
Tested with the 2 latest build.

**crash.log**
[https://pastebin.com/YpnAgQKh](https://pastebin.com/YpnAgQKh)

**Comment by chenxiaolong** [comment]
Thanks for the logs! I'll take a look after I get back from my business trip later this week.

**Comment by tone361** [comment]
logs on both of my phones mt6572...
[crash1.log](https://github.com/chenxiaolong/DualBootPatcher/files/1682798/crash1.log)
[crash.log](https://github.com/chenxiaolong/DualBootPatcher/files/1682797/crash.log)

**Comment by xc920718** [comment]
If you upgrade from a low version to a high version.it will be work,such as r321 to r362 .

**Comment by tone361** [comment]
nope is not working tried....

**Comment by electricboy207** [comment]
Also getting this problem, I'll post the logs.

**Comment by electricboy207** [comment]
[crash.log.zip](https://github.com/chenxiaolong/DualBootPatcher/files/1692151/crash.log.zip)

**Comment by electricboy207** [comment]
I'm not sure if this is related to the Mbtools error, but trying to install a patched Rom does so successfully but when rebooting it gets to the "N/A" screen, then reboots into twrp.

**Comment by chenxiaolong** [comment]
@klorinczi I believe your crash is a different issue. It should be fixed by #996. Please give version `9.3.0.r382.gbed62d35` a try.

@tone361 Which APK are you using? Is it an official version? The error you're running into is a different one.

**Comment by electricboy207** [comment]
@chenxiaolong I tried to update ramdisk and it crashed then rebooted to twrp.

**Comment by electricboy207** [comment]
[20180203.175123.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/1692284/20180203.175123.tar.gz)

**Comment by benkhouya** [comment]
Tested with version 9.3.0.r382.gbed62d35 on SM-J510F (j5xnltejv) rooted with Magisk 15.3
The app crash after clicking the _parameter_ menu.

**crash.log** https://pastebin.com/XrUJqXDz
**boot-ui-action.log** https://pastebin.com/xHE0vZUz

**Comment by electricboy207** [comment]
Tried again in Resurrection Remix and it failed again.

**Comment by electricboy207** [comment]
It seems like the radial update is the problem

**Comment by klorinczi** [comment]
@chenxiaolong: Tested and seems to work fine now, doesn't crash. Fix #996 was successful. 
Thank you very much!

**Comment by tone361** [comment]
Yes official one r362...

**Comment by tone361** [comment]
@chenxiaolong even on newer versions I get this error

**Comment by Rybens92** [comment]
On Oneplus 5T with magisk 15.3 root, with 382 snapshot of DBP.
Crash I get when I come to Rom section of app:
https://pastebin.com/rXxEDKUT

**Comment by chenxiaolong** [comment]
This should be fixed by #997 (version `9.3.0.r387.gbcd16c1a`)

**Comment by tone361** [comment]
May be is from my yml file something might be wrong there....cuz I got another crash at roms section..when it says cannot start mbtool root needed after I give it root access it says dualboot patcher has crashed and it closes itself..

**Comment by klorinczi** [comment]
@tone361: You should test it with 9.3.0.r387.gbcd16c1a installed, and if still crashing, you should post the error logs again.

**Comment by klorinczi** [comment]
BTW: latest is 9.3.0.r404.g40d5304a. Should test crash with this version.

**Comment by tone361** [comment]
made another open issue but I need to mention that i'm using 4.4.2 kitkat

**Comment by benkhouya** [comment]
When access to rom section on DBP 9.3.0.r404.g40d5304a - Galaxy J5 (2016) SM-J510F (j5xnltejv)
**crash.log** : https://pastebin.com/ieKf5eBy

**Comment by tone361** [comment]
https://pastebin.com/4svLXdwD
